export const ERROR_CODES = {
  WORKSPACE_ID_REQUIRED: 'WORKSPACE_ID_REQUIRED',
  STAGE_NOT_FOUND: 'STAGE_NOT_FOUND',
  OPPORTUNITY_NOT_FOUND: 'OPPORTUNITY_NOT_FOUND',
  BULK_MOVE_JOB_NOT_FOUND: 'BULK_MOVE_JOB_NOT_FOUND',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INVALID_CURSOR: 'INVALID_CURSOR',
  DTO_VALIDATION_FAILED: 'DTO_VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
