export const ERROR_CODES = {
  WORKSPACE_ID_REQUIRED: 'WORKSPACE_ID_REQUIRED',
  OPPORTUNITY_FIELDS_REQUIRED: 'OPPORTUNITY_FIELDS_REQUIRED',
  OPPORTUNITY_STATUS_INVALID: 'OPPORTUNITY_STATUS_INVALID',
  STAGE_NOT_FOUND: 'STAGE_NOT_FOUND',
  MOVE_FIELDS_REQUIRED: 'MOVE_FIELDS_REQUIRED',
  OPPORTUNITY_NOT_FOUND: 'OPPORTUNITY_NOT_FOUND',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INVALID_CURSOR: 'INVALID_CURSOR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
